#!/bin/bash
export http_proxy=http://xxxx.xxxx.xxxx.xxxx:80/ 
export ftp_proxy=ftp://xxxx.xxxx.xxxx.xxxx:80/ 
export socks_proxy=socks://xxxx.xxxx.xxxx.xxxx:80/ 
export https_proxy=https://xxxx.xxxx.xxxx.xxxx:80/ 

SED=$(test $(uname -o) = 'Darwin' && echo gsed || echo sed)

if [ -z $(git config --global --name-only -l |grep remote.origin.proxy |xargs) ] 
then 
    git config --global --add remote.origin.proxy ""
fi
$SED -i 's/proxy.*/proxy = xxxx\.xxxx\.xxxx\.xxxx:80/' ~/.gitconfig

if [ -z $(git config --global --name-only -l |grep user.name |xargs) ] 
then 
    git config --global --add user.name ""
fi
$SED -i 's/name.*/name = xxxx/' ~/.gitconfig

if [ -z $(git config --global --name-only -l |grep user.email |xargs) ] 
then 
    git config --global --add user.email ""
fi
$SED -i 's/email.*/email = xxxx@xxxx.xxxx/' ~/.gitconfig
